/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSculpturesSculpture.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sculptures/v1
// Description:
//   Sculpture API
// Classes:
//   GTLSculpturesSculpture (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLSculpturesSculpture
//

@interface GTLSculpturesSculpture : GTLObject
@property (nonatomic, copy) NSString *artist;
@property (nonatomic, copy) NSString *audio;  // GTLBase64 can encode/decode (probably web-safe format)

// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (nonatomic, copy) NSString *descriptionProperty;

@property (nonatomic, copy) NSString *entityKey;
@property (nonatomic, copy) NSString *image;
@property (nonatomic, copy) NSString *location;
@property (nonatomic, copy) NSString *title;
@end
