/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSculpturesArtist.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sculptures/v1
// Description:
//   Sculpture API
// Classes:
//   GTLSculpturesArtist (0 custom class methods, 5 custom properties)

#import "GTLSculpturesArtist.h"

// ----------------------------------------------------------------------------
//
//   GTLSculpturesArtist
//

@implementation GTLSculpturesArtist
@dynamic descriptionProperty, entityKey, fname, lname, websiteUrl;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"descriptionProperty" : @"description",
    @"websiteUrl" : @"website_url"
  };
  return map;
}

@end
