/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSculpturesSculpture.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sculptures/v1
// Description:
//   Sculpture API
// Classes:
//   GTLSculpturesSculpture (0 custom class methods, 7 custom properties)

#import "GTLSculpturesSculpture.h"

// ----------------------------------------------------------------------------
//
//   GTLSculpturesSculpture
//

@implementation GTLSculpturesSculpture
@dynamic artist, audio, descriptionProperty, entityKey, image, location, title;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"descriptionProperty" : @"description"
  };
  return map;
}

@end
