/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSculptures_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sculptures/v1
// Description:
//   Sculpture API

#import "GTLSculpturesConstants.m"

#import "GTLSculpturesArtist.m"
#import "GTLSculpturesArtistCollection.m"
#import "GTLSculpturesComment.m"
#import "GTLSculpturesCommentCollection.m"
#import "GTLSculpturesSculpture.m"
#import "GTLSculpturesSculptureCollection.m"

#import "GTLQuerySculptures.m"
#import "GTLServiceSculptures.m"
