/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSculpturesConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sculptures/v1
// Description:
//   Sculpture API

#import "GTLSculpturesConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeSculpturesUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
