/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSculpturesCommentCollection.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sculptures/v1
// Description:
//   Sculpture API
// Classes:
//   GTLSculpturesCommentCollection (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLSculpturesComment;

// ----------------------------------------------------------------------------
//
//   GTLSculpturesCommentCollection
//

// This class supports NSFastEnumeration over its "items" property. It also
// supports -itemAtIndex: to retrieve individual objects from "items".

@interface GTLSculpturesCommentCollection : GTLCollectionObject
@property (nonatomic, retain) NSArray *items;  // of GTLSculpturesComment
@property (nonatomic, copy) NSString *nextPageToken;
@end
