/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSculpturesArtistCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sculptures/v1
// Description:
//   Sculpture API
// Classes:
//   GTLSculpturesArtistCollection (0 custom class methods, 2 custom properties)

#import "GTLSculpturesArtistCollection.h"

#import "GTLSculpturesArtist.h"

// ----------------------------------------------------------------------------
//
//   GTLSculpturesArtistCollection
//

@implementation GTLSculpturesArtistCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLSculpturesArtist class]
  };
  return map;
}

@end
