/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSculptures.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sculptures/v1
// Description:
//   Sculpture API

#import "GTLSculpturesConstants.h"

#import "GTLSculpturesArtist.h"
#import "GTLSculpturesArtistCollection.h"
#import "GTLSculpturesComment.h"
#import "GTLSculpturesCommentCollection.h"
#import "GTLSculpturesSculpture.h"
#import "GTLSculpturesSculptureCollection.h"

#import "GTLQuerySculptures.h"
#import "GTLServiceSculptures.h"
