/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSculpturesComment.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sculptures/v1
// Description:
//   Sculpture API
// Classes:
//   GTLSculpturesComment (0 custom class methods, 5 custom properties)

#import "GTLSculpturesComment.h"

// ----------------------------------------------------------------------------
//
//   GTLSculpturesComment
//

@implementation GTLSculpturesComment
@dynamic author, content, entityKey, sculptureKey, timestamp;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"sculptureKey" : @"sculpture_key"
  };
  return map;
}

@end
