/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSculpturesSculptureCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sculptures/v1
// Description:
//   Sculpture API
// Classes:
//   GTLSculpturesSculptureCollection (0 custom class methods, 2 custom properties)

#import "GTLSculpturesSculptureCollection.h"

#import "GTLSculpturesSculpture.h"

// ----------------------------------------------------------------------------
//
//   GTLSculpturesSculptureCollection
//

@implementation GTLSculpturesSculptureCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLSculpturesSculpture class]
  };
  return map;
}

@end
