/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLServiceSculptures.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sculptures/v1
// Description:
//   Sculpture API
// Classes:
//   GTLServiceSculptures (0 custom class methods, 0 custom properties)

#import "GTLSculptures.h"

@implementation GTLServiceSculptures

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = @[
    [GTLQuerySculptures class],
    [GTLSculpturesArtist class],
    [GTLSculpturesArtistCollection class],
    [GTLSculpturesComment class],
    [GTLSculpturesCommentCollection class],
    [GTLSculpturesSculpture class],
    [GTLSculpturesSculptureCollection class]
  ];
  return classes;
}
#endif  // DEBUG

- (instancetype)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://thassculptures.appspot.com/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
