/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSculpturesCommentCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sculptures/v1
// Description:
//   Sculpture API
// Classes:
//   GTLSculpturesCommentCollection (0 custom class methods, 2 custom properties)

#import "GTLSculpturesCommentCollection.h"

#import "GTLSculpturesComment.h"

// ----------------------------------------------------------------------------
//
//   GTLSculpturesCommentCollection
//

@implementation GTLSculpturesCommentCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLSculpturesComment class]
  };
  return map;
}

@end
